server:
  port: 8080

spring:
  application:
    name: module-api

  datasource:
    url: jdbc:h2:tcp://localhost/~/dev/h2/yummy
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true